name       : python-dateutil
version    : 2.4.2
release    : 2
source     :
    - https://pypi.python.org/packages/source/p/python-dateutil/python-dateutil-2.4.2.tar.gz : 3e95445c1db500a344079a47b171c45ef18f57d188dffdb0e4165c71bea8eb3d
license    : BSD-2-Clause
summary    : Python Date Module
description: |
    The dateutil module provides powerful extensions to the datetime module available in the Python standard library.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
    - python3-setuptools
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
