name       : python-dateutil
version    : 2.8.2
release    : 21
source     :
    - https://pypi.python.org/packages/source/p/python-dateutil/python-dateutil-2.8.2.tar.gz : 0123cacc1627ae19ddf3c27a5de5bd67ee4586fbdd6440d9748f8abb483d3e86
homepage   : https://github.com/dateutil/dateutil
license    :
    - Apache-2.0
    - BSD-3-Clause
component  : programming.python
summary    : Python date module
description: |
    The dateutil module provides powerful extensions to the datetime module available in the Python standard library.
builddeps  :
    - python-freezegun
    - python-hypothesis
    - python-pytest
    - python-setuptools-scm
rundeps    :
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test pytest3
