name       : python-dateutil
version    : 2.6.0
release    : 4
source     :
    - https://pypi.python.org/packages/51/fc/39a3fbde6864942e8bb24c93663734b74e281b984d1b8c4f95d64b0c21f6/python-dateutil-2.6.0.tar.gz : 62a2f8df3d66f878373fd0072eacf4ee52194ba302e00082828e0d263b0418d2
license    : BSD-2-Clause
component  : programming.python
summary    : Python Date Module
description: |
    The dateutil module provides powerful extensions to the datetime module available in the Python standard library.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install --no-compile -O0
    %python3_install --no-compile -O0
