name       : python-dateutil
version    : 2.8.1
release    : 13
source     :
    - https://pypi.python.org/packages/source/p/python-dateutil/python-dateutil-2.8.1.tar.gz : 73ebfe9dbf22e832286dafa60473e4cd239f8592f699aa5adaf10050e6e1823c
license    :
    - Apache-2.0
    - BSD-3-Clause
component  : programming.python
summary    : Python date module
description: |
    The dateutil module provides powerful extensions to the datetime module available in the Python standard library.
builddeps  :
    - python-freezegun
    - python-hypothesis
    - python-pytest
    - python-setuptools
    - python-setuptools-scm
rundeps    :
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
#check      : |
#    %python_test pytest
#    %python3_test pytest3
