name       : python-dateutil
version    : 2.6.1
release    : 7
source     :
    - https://github.com/dateutil/dateutil/archive/2.6.1.tar.gz : ea1872b3296efca80dec69aef6217895d7776008fcfba3532fb53bbdc7814ad1
license    : BSD-2-Clause
component  : programming.python
summary    : Python Date Module
description: |
    The dateutil module provides powerful extensions to the datetime module available in the Python standard library.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install --no-compile -O0
    %python3_install --no-compile -O0
